# Linear Discriminant Analysis

In [1]:
# Setup Libraries - if needed
%matplotlib inline
import pandas as pd
import sklearn
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
plt.style.use('ggplot')

In [2]:
# import the training data
training = pd.read_csv('training.csv',index_col= 'idx' )


# view the data
training.head()

SeriousDlqin2yrs  RevolvingUtilizationOfUnsecuredLines  age  \
idx                                                                
1                   1                              0.766127   45   
2                   0                              0.957151   40   
3                   0                              0.658180   38   
4                   0                              0.233810   30   
5                   0                              0.907239   49   

     NumberOfTime30to59DaysPastDueNotWorse  DebtRatio  MonthlyIncome  \
idx                                                                    
1                                        2   0.802982           9120   
2                                        0   0.121876           2600   
3                                        1   0.085113           3042   
4                                        0   0.036050           3300   
5                                        1   0.024926          63588   

     NumberOfOpenCreditLinesAndLoans  NumberOfTimes90DaysLate  \
idx                                                             
1                                 13                        0   
2                                  4                        0   
3                                  2                        1   
4                                  5                        0   
5                                  7                        0   

     NumberRealEstateLoansOrLines  NumberOfTime60to89DaysPastDueNotWorse  \
idx                                                                        
1                               6                                      0   
2                               0                                      0   
3                               0                                      0   
4                               0                                      0   
5                               1                                      0   

     NumberOfDependents  
idx                      
1                     2  
2                     1  
3                     0  
4                     0  
5                     0

In [3]:
# Import SciKit Learn functions
from sklearn.metrics import roc_curve, auc , roc_auc_score, confusion_matrix
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis 
from sklearn.cross_validation import train_test_split

In [5]:
# Split the target from the input variables
X = training.iloc[:, 1:]
y = training.iloc[:, 0]

In [6]:
def LDA_ITER(n):
    global AUC
    AUC = []    
    for x in range(0, n):
        # Split the data into training and testing sets
        X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=x)
        print X_train.shape 
        print X_test.shape 
        print y_train.shape 
        print y_test.shape
        # Create the LDA object7 
        LDA = LinearDiscriminantAnalysis(solver='svd', shrinkage=None, priors=None, n_components=None, store_covariance=False)

        # Fit to the data
        LDAfit = LDA.fit(X_train,y_train)

        # Output model evaluation
        LDApred = LDA.predict(X_test)
        print "The confusion matrix is " 
        print confusion_matrix(y_test, LDApred)
        print "The area under the curve is" , roc_auc_score(y_test, LDApred)
        xx = roc_auc_score(y_test, LDApred)
        AUC.append(xx)

    
LDA_ITER(10)

print "The average AUC score is" , np.mean(AUC)

(112500, 10)
(37500, 10)
(112500L,)
(37500L,)
The confusion matrix is 
[[34710   243]
 [ 2296   251]]
The area under the curve is 0.545797558808
(112500, 10)
(37500, 10)
(112500L,)
(37500L,)
The confusion matrix is 
[[34749   219]
 [ 2277   255]]
The area under the curve is 0.547224015783
(112500, 10)
(37500, 10)
(112500L,)
(37500L,)
The confusion matrix is 
[[34698   246]
 [ 2281   275]]
The area under the curve is 0.550275074593
(112500, 10)
(37500, 10)
(112500L,)
(37500L,)
The confusion matrix is 
[[34774   253]
 [ 2206   267]]
The area under the curve is 0.550371516879
(112500, 10)
(37500, 10)
(112500L,)
(37500L,)
The confusion matrix is 
[[34706   238]
 [ 2309   247]]
The area under the curve is 0.544912235163
(112500, 10)
(37500, 10)
(112500L,)
(37500L,)
The confusion matrix is 
[[34748   210]
 [ 2287   255]]
The area under the curve is 0.547153752087
(112500, 10)
(37500, 10)
(112500L,)
(37500L,)
The confusion matrix is 
[[34826   234]
 [ 2173   267]]
The area under the curve is 

## Evaluation

The results of the Linear Discriminant Analysis do not perform well. They are only marginally better than logistic regression with an AUC score of 0.548207825381 . There are a number of assumptions that come into play when using Linear Discriminant Analysis. The most important of them being that the conditional distribution of our features given the target are gaussian distributed. This can be an unreasonable expectation.

## AUC = 0.548207825381